# Global settings.
Global:
  # Whether or not to notify the player when their items are gathered and restored.
  Notify: true
  # Message header color
  Color: gold
  # Message text color
  TextColor: white
  # Enable this for permission based per item exclusions. See online documentation for details.
  SingleItemDrops: false
  # If SingleItemDrops is true and SingleItemDropsOnly is false then only explicitely denied drops will be dropped. If this is true then you must explicetly allow players to keep each item and everything else is dropped.
  SingleItemDropsOnly: false
  Debug: false
  Permissions: true
  OpsAllPerms: false
  # If true then Scavenger will not recover items in a WorldGuard PVP zone.
  WorldGuardPVPIgnore: false
  # If true then restores only work in PVP zones.
  WorldGuardPVPOnly: false
Messages:
  MsgRecovered: Your inventory has been restored.
  MsgSaving: Saving your inventory.
  MsgSaveForFee: Saving your inventory for a small fee of %COST% %CURRENCY%.
  MsgNotEnoughMoney: Item recovery cost is %COST% and you only have %BALANCE% %CURRENCY%.
  MsgInsidePA: You are inside PVP Arena %ARENA%. Scavenger will not save your inventory.
  MsgInsideMA: You are inside a Mob Arena. Scavenger will not save your inventory.
  MsgInsideWGPVP: You are inside a WorldGuard PVP region. Scavenger will not save your inventory.
  MsgInsideWGPVPOnly: You are not inside a WorldGuard PVP region. Scavenger will not save your inventory.
Economy:
    # Whether or not to use an economy system with the plugin.
    Enabled: false
    # Percentage mode
    Percent: false
    # The cost of restoring your inventory (if enabled).
    RestoreCost: 10.0
    # Minimum cost if using percent (0 for no min cost)
    MinCost: 5.0    
    # Maximum cost if using percent (0 for no max cost)
    MaxCost: 0
    # Percentage to withdraw
    PercentCost: 5.0
    # Calculate cost as MinCost + RestoreCost
    AddMin: false