# Global settings.
Global:
  # Whether or not to notify the player when their items are gathered and restored.
  Notify: true
Economy:
    # Whether or not to use an economy system with the plugin.
    Enabled: false
    # The cost of restoring your inventory (if enabled).
    RestoreCost: 10.0

