name: Scavenger
main: me.cnaude.plugin.Scavenger.Scavenger
version: 1.6.9-TEST1
author: Chris Naudé 
description: Item recovery on death. Based on SirHedgehog's code.
website: http://dev.bukkit.org/server-mods/scavenger/
softdepend: [Vault]
commands:
  scavengerreload:
    description: Reload config
    usage: /scavengerreload
    aliases: scvr
  scvron:
    description: Self enable item recovery.
    usage: /scvron
    aliases: scavengeron   
  scvroff:
    description: Self disable item recovery.
    usage: /scvroff
    aliases: scavengeroff
permissions:
  scavenger.scavenge:
    description: Allows players to automatically recover items on death.
    default: false
  scavenger.free:
    description: Free item recovery.
    default: false
  scavenger.reload:
    description: Reload config.
    default: op
  scavenger.level:
    description: Allows players to automatically recover experience level on death.
    default: false
  scavenger.exp:
    description: Allows players to automatically recover experience (towards next level) on death.
    default: false
  scavenger.self.on:
    description: Allows players to enable item recovery for themselves.
    default: false
  scavenger.self.off:
    description: Allows players to disable item recovery for themselves.
    default: false
