name: Scavenger
main: me.cnaude.plugin.Scavenger.Scavenger
version: 1.6
author: Chris Naudé 
description: Item based Player to Player realistically rendered mail. Based on SirHedgehog's code.
website: http://forums.bukkit.org/threads/sec-mech-scavenger-v1-4-0-item-recovery-on-death-permissions-iconomy-4-5-1-1-r4.16544/
softdepend: [Vault]
permissions:
scavenger.scavenge:
  description: Allows players to automatically recover items on death.
  default: op
scavenger.free:
  description: Free item recovery.
  default: op
